Repository marcosdosea/Alugai, pull requests merged in 2021-02, with the labels that each got.

#116 Ajustes gerais e alteração de campo
  Codigo/Alugai/AlugaiWEB/Controllers/DespesasController.cs
  Codigo/Alugai/AlugaiWEB/Models/DespesasModel.cs
  Codigo/Alugai/AlugaiWEB/Views/Despesas/Create.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Despesas/Delete.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Despesas/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Despesas/Edit.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Despesas/Index.cshtml
Labels: bug, enhancement

#125 Alteração de campo e correção de bug no cadastro
  Codigo/Alugai/.vs/Alugai/config/applicationhost.config
  Codigo/Alugai/AlugaiWEB/Controllers/AnuncioController.cs
  Codigo/Alugai/AlugaiWEB/Models/AnuncioModel.cs
  Codigo/Alugai/AlugaiWEB/Views/Anuncio/Create.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Anuncio/Edit.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Anuncio/Index.cshtml
Labels: bug, enhancement

#126 Alteração de campo do aluguel
  Codigo/Alugai/AlugaiWEB/Controllers/AluguelController.cs
  Codigo/Alugai/AlugaiWEB/Models/AluguelModel.cs
  Codigo/Alugai/AlugaiWEB/Views/Aluguel/Create.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Aluguel/Edit.cshtml
Labels: enhancement

#127 Alteração de campo no pagamento
  Codigo/Alugai/.vs/Alugai/DesignTimeBuild/.dtbcache.v2
  Codigo/Alugai/.vs/Alugai/config/applicationhost.config
  Codigo/Alugai/AlugaiWEB/Controllers/PagamentoController.cs
  Codigo/Alugai/AlugaiWEB/Models/PagamentoModelcs.cs
  Codigo/Alugai/AlugaiWEB/Views/Pagamento/Create.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pagamento/Edit.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pagamento/Index.cshtml
Labels: enhancement

#133 Implementação do Menu Lateral no Caso de Uso manter aluguel.
  Codigo/Alugai/.vs/Alugai/DesignTimeBuild/.dtbcache.v2
  Codigo/Alugai/.vs/Alugai/config/applicationhost.config
  Codigo/Alugai/AlugaiWEB/Views/Aluguel/Index.cshtml
Labels: enhancement

#136 Criado tela para exibir as informações gerenciais do sistema
  Codigo/Alugai/.vs/Alugai/DesignTimeBuild/.dtbcache.v2
  Codigo/Alugai/.vs/Alugai/config/applicationhost.config
  Codigo/Alugai/AlugaiWEB/Views/MeusDados/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Shared/_Layout.cshtml
  Codigo/Alugai/AlugaiWEB/wwwroot/css/style.css
Labels: enhancement

#137 Ajustes index imóvel
  Codigo/Alugai/AlugaiWEB/Models/ImovelModel.cs
  Codigo/Alugai/AlugaiWEB/Views/Imovel/Index.cshtml
Labels: enhancement

#138 Ajustes listagem pessoa
  Codigo/Alugai/AlugaiWEB/Models/PessoaModel.cs
  Codigo/Alugai/AlugaiWEB/Views/Pessoa/Index.cshtml
Labels: enhancement

#139 Prototipado listagem de anúncios
  Codigo/Alugai/AlugaiWEB/Views/Home/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Shared/_Layout.cshtml
  Codigo/Alugai/AlugaiWEB/wwwroot/css/style.css
  Codigo/Alugai/AlugaiWEB/wwwroot/imagens/casa01.jpg
Labels: enhancement

#140 Criado MeusDados Controller
  Codigo/Alugai/.vs/Alugai/DesignTimeBuild/.dtbcache.v2
  Codigo/Alugai/AlugaiWEB/Controllers/MeusDadosController.cs
  Codigo/Alugai/AlugaiWEB/Views/MeusDados/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Shared/_Layout.cshtml
  Codigo/Alugai/AlugaiWEB/wwwroot/css/style.css
Labels: enhancement

#142 Padronização do layout
  Codigo/Alugai/AlugaiWEB/Views/Aluguel/Create.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Aluguel/Delete.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Aluguel/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Aluguel/Edit.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Aluguel/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Anuncio/Create.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Anuncio/Delete.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Anuncio/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Anuncio/Edit.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Anuncio/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/DeclaracaoAluguel/Create.cshtml
  Codigo/Alugai/AlugaiWEB/Views/DeclaracaoAluguel/Delete.cshtml
  Codigo/Alugai/AlugaiWEB/Views/DeclaracaoAluguel/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/DeclaracaoAluguel/Edit.cshtml
  Codigo/Alugai/AlugaiWEB/Views/DeclaracaoAluguel/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Despesas/Create.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Despesas/Delete.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Despesas/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Despesas/Edit.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Despesas/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Imovel/Create.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Imovel/Delete.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Imovel/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Imovel/Edit.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pagamento/Create.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pagamento/Delete.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pagamento/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pagamento/Edit.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pagamento/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pessoa/Create.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pessoa/Delete.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pessoa/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pessoa/Edit.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pessoa/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Shared/_MeusDados.cshtml
  Codigo/Alugai/AlugaiWEB/Views/SolicitacaoManutencao/Create.cshtml
  Codigo/Alugai/AlugaiWEB/Views/SolicitacaoManutencao/Delete.cshtml
  Codigo/Alugai/AlugaiWEB/Views/SolicitacaoManutencao/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/SolicitacaoManutencao/Edit.cshtml
  Codigo/Alugai/AlugaiWEB/Views/SolicitacaoManutencao/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Statuspagamento/Create.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Statuspagamento/Delete.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Statuspagamento/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Statuspagamento/Edit.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Statuspagamento/Index.cshtml
Labels: enhancement

#143 Ajustes botões e model
  Codigo/Alugai/.vs/Alugai/DesignTimeBuild/.dtbcache.v2
  Codigo/Alugai/AlugaiWEB/Models/DespesasModel.cs
  Codigo/Alugai/AlugaiWEB/Models/ImovelModel.cs
  Codigo/Alugai/AlugaiWEB/Models/PagamentoModelcs.cs
  Codigo/Alugai/AlugaiWEB/Models/SolicitacaoManuntecaoModel.cs
  Codigo/Alugai/AlugaiWEB/Views/Aluguel/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Aluguel/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Anuncio/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Anuncio/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/DeclaracaoAluguel/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/DeclaracaoAluguel/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Despesas/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Despesas/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Imovel/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Imovel/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pagamento/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pagamento/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pessoa/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Pessoa/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Shared/_Layout.cshtml
  Codigo/Alugai/AlugaiWEB/Views/SolicitacaoManutencao/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/SolicitacaoManutencao/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Statuspagamento/Details.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Statuspagamento/Index.cshtml
Labels: enhancement

#144 Prototipado header para exibição dos filtros
  Codigo/Alugai/AlugaiWEB/AlugaiWEB.csproj
  Codigo/Alugai/AlugaiWEB/Views/Home/Index.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Shared/_Layout.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Shared/_filtersHeader.cshtml
  Codigo/Alugai/AlugaiWEB/wwwroot/css/style.css
  Codigo/Alugai/AlugaiWEB/wwwroot/imagens/cabecalho.jpg
Labels: enhancement

#147 Ajustado conteudo do header quebrando
  Codigo/Alugai/.vs/Alugai/DesignTimeBuild/.dtbcache.v2
  Codigo/Alugai/.vs/Alugai/config/applicationhost.config
  Codigo/Alugai/AlugaiWEB/.vscode/launch.json
  Codigo/Alugai/AlugaiWEB/.vscode/tasks.json
  Codigo/Alugai/AlugaiWEB/wwwroot/css/footer-with-button-logo.css
Labels: bug

#148 Foi criado a tela do cadastro de pessoa
  Codigo/Alugai/.vs/Alugai/DesignTimeBuild/.dtbcache.v2
  Codigo/Alugai/AlugaiWEB/Models/PessoaModel.cs
  Codigo/Alugai/AlugaiWEB/Views/Pessoa/Create.cshtml
  Codigo/Alugai/AlugaiWEB/Views/Shared/_filtersHeader.cshtml
Labels: enhancement

#150 Foi adicionado um ícone do usuário com opção de logoff
  Codigo/Alugai/.vs/Alugai/DesignTimeBuild/.dtbcache.v2
  Codigo/Alugai/.vs/Alugai/config/applicationhost.config
  Codigo/Alugai/AlugaiWEB/Properties/launchSettings.json
  Codigo/Alugai/AlugaiWEB/Views/Shared/_MeusDados.cshtml
  Codigo/Alugai/AlugaiWEB/wwwroot/css/style.css
Labels: enhancement

#151 Ajuste cursor
  Codigo/Alugai/AlugaiWEB/Views/Shared/_MeusDados.cshtml
  Codigo/Alugai/AlugaiWEB/wwwroot/css/style.css
Labels: enhancement

#153 Foi feito pequenos ajustes nas telas de Login e Resgistrar novo usuario.
  Codigo/Alugai/.vs/Alugai/DesignTimeBuild/.dtbcache.v2
  Codigo/Alugai/.vs/Alugai/config/applicationhost.config
  Codigo/Alugai/AlugaiWEB/Areas/Identity/Pages/Account/ExternalLogin.cshtml
  Codigo/Alugai/AlugaiWEB/Areas/Identity/Pages/Account/Login.cshtml
  Codigo/Alugai/AlugaiWEB/Areas/Identity/Pages/Account/Register.cshtml
  Codigo/Alugai/AlugaiWEB/Areas/Identity/Pages/Account/ResetPassword.cshtml
Labels: enhancement
